require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/comments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Comment. As you add validations to Comment, be sure to
  # adjust the attributes here as well.
  let!(:user) { create :user }
  let!(:comment) { create :comment }

  let(:valid_attributes) {
    {
      body: "Wonderful post",
    }
  }

  let(:invalid_attributes) {
    {
      body: "",
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CommentsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {
      'Authorization': token_for(user),
    }
  }

  describe "POST /create" do
    it "returns 401 unauthorized when user is unauthenticated" do
      post post_comments_url(comment.post), params: { comment: valid_attributes },
                                            as: :json
      expect(response).to have_http_status(:unauthorized)
    end

    context "with valid parameters" do
      it "creates a new Comment" do
        expect {
          post post_comments_url(comment.post),
               params: { comment: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Comment, :count).by(1)
      end

      it "renders a JSON response with the new comment" do
        post post_comments_url(comment.post),
             params: { comment: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Comment" do
        expect {
          post post_comments_url(comment.post),
               params: { comment: invalid_attributes }, as: :json
        }.to change(Comment, :count).by(0)
      end

      it "renders a JSON response with errors for the new comment" do
        post post_comments_url(comment.post, comment),
             params: { comment: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "returns 401 unauthorized when user is unauthenticated" do
      delete post_comment_url(comment.post, comment), as: :json
      expect(response).to have_http_status(:unauthorized)
    end

    it "returns 403 forbidden when user is not owner of comment" do
      delete post_comment_url(comment.post, comment), headers: valid_headers, as: :json
      expect(response).to have_http_status(:forbidden)
      expect(json["message"]).to eq "Only the author of the comment is allowed perform this operation"
    end

    it "destroys the requested comment" do
      c = create :comment, user: user
      expect {
        delete post_comment_url(c.post, c), headers: valid_headers, as: :json
      }.to change(Comment, :count).by(-1)
    end
  end
end
