require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/posts", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Post. As you add validations to Post, be sure to
  # adjust the attributes here as well.
  let!(:user) { create :user }

  let(:valid_attributes) {
    {
      body: "My awesome post",
    }
  }

  let(:invalid_attributes) {
    {
      body: "",
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # PostsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let!(:valid_headers) {
    {
      'Authorization': token_for(user),
    }
  }

  describe "PUT /like" do
    let!(:post1) { create :post }

    it "returns 401 unauthorized when user is unauthenticated" do
      put like_post_url(post1), as: :json
      expect(response).to have_http_status(:unauthorized)
    end

    it "likes post" do
      put like_post_url(post1), as: :json, headers: valid_headers
      post1.reload
      expect(post1.likes.count).to eq 1
    end
  end

  describe "PUT /unlike" do
    let!(:post1) { create :post }

    it "returns 401 unauthorized when user is unauthenticated" do
      put unlike_post_url(post1), as: :json
      expect(response).to have_http_status(:unauthorized)
    end

    it "unlikes post" do
      create :like, likable: post1, user: user
      post1.reload
      expect(post1.likes.count).to eq 1
      put unlike_post_url(post1), as: :json, headers: valid_headers
      post1.reload
      expect(post1.likes.count).to eq 0
    end
  end

  describe "GET /index" do
    it "renders a successful response" do
      create(:post)
      get posts_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end

    it "returns # of likes for each post" do
      post1 = create(:post)
      random = rand(10)
      create_list :like, random, likable: post1
      get posts_url, headers: valid_headers, as: :json
      expect(json["data"][0]["likes"]).to eq random
    end

    it "returns image_url for posts with images" do
      # first create post with image
      valid_attributes[:image] = Rack::Test::UploadedFile.new("#{Rails.root}/spec/fixtures/user.jpg")
      post posts_url, xhr: true,
                      params: { post: valid_attributes }, headers: valid_headers

      get posts_url, headers: valid_headers, as: :json
      expect(json["data"][0]["image_url"]).not_to be_nil
    end

    it "returns user details along with each post" do
      p = create(:post)
      get posts_url, headers: valid_headers, as: :json
      expect(json["data"][0]["user"]["name"]).to eq p.user.name
      expect(json["data"][0]["user"]["email"]).to be_nil
      expect(json["data"][0]["user"]["id"]).to eq p.user.id
      expect(json["data"][0]["user"]["url"]).to eq user_url(p.user, format: :json)
    end

    it "returns 401 unauthorized when user is unauthenticated" do
      get posts_url, as: :json
      expect(response).to have_http_status(:unauthorized)
    end

    context "many posts" do
      before do
        create_list :post, rand((rand(2..3) * Post.per_page)..(rand(4..6) * Post.per_page))
        get "/posts", xhr: true, headers: valid_headers
      end

      it "returns a paginated list of posts" do
        expect(json["data"].length).to eq(Post.per_page)
        expect(json["_pagination"]["count"] <= Post.per_page).to be_truthy
        expect(json["_pagination"]["total_count"]).to eq Post.count
        expect(json["_links"]["next_page"]).not_to be_nil
        expect(json["_links"]["prev_page"]).to be_nil
        expect(json["_links"]).not_to be_nil
        total_pages = (Post.count.to_f / Post.per_page).ceil
        expect(json["_pagination"]["total_pages"]).to eq total_pages
        expect(json["_pagination"]["total_count"]).to eq Post.count
        expect(json["_links"]["last_page"]).to eq posts_url(page: total_pages)

        get json["_links"]["last_page"], headers: valid_headers, xhr: true
        expect(json["_links"]["next_page"]).to be_nil
        expect(json["_links"]["prev_page"]).not_to be_nil
        expect(json["data"].length <= Post.per_page).to be_truthy
      end

      it "orders results in descending order of creation time" do
        expect(json["data"][0]["id"] > json["data"][-1]["id"]).to be_truthy
      end
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      post1 = create(:post)
      get post_url(post1), headers: valid_headers, as: :json
      expect(response).to have_http_status(:ok)
    end

    it "returns 401 unauthorized when user is unauthenticated" do
      get post_url(create :post), as: :json
      expect(response).to have_http_status(:unauthorized)
    end

    context "with likes" do
      it "returns # of likes for each post" do
        post1 = create(:post)
        random = rand(10)
        create_list :like, random, likable: post1
        get posts_url, headers: valid_headers, as: :json
        expect(json["data"][0]["likes"]).to eq random
      end

      it "paginates post likes in ascending order of creation time" do
        post1 = create :post
        random_count = rand((rand(2..4) * Like.per_page)..(rand(5..8) * Like.per_page))
        create_list(:like, random_count, likable: post1)

        token = token_for(create :user)
        @opts = { xhr: true, headers: { 'Authorization': token } }
        get post_url(post1), **@opts

        index = rand Like.per_page
        expect(json["users_liked"]["data"][index]["id"]).to eq post1.likes[index].user.id
        expect(json["users_liked"]["data"][index]["name"]).to eq post1.likes[index].user.name

        # check ascending order
        expect(json["users_liked"]["data"][0]["id"] < json["users_liked"]["data"][-1]["id"]).to be_truthy

        expect(json["users_liked"]["data"].length).to eq(Like.per_page)
        expect(json["users_liked"]["_pagination"]["count"] <= Like.per_page).to be_truthy
        expect(json["users_liked"]["_pagination"]["total_count"]).to eq(post1.likes.count)
        expect(json["users_liked"]["_links"]["next_page"]).to eq(post_url(post1, likes_page: 2))
        total_likes_page = (post1.likes.count / Like.per_page.to_f).ceil
        expect(json["users_liked"]["_links"]["last_page"]).to eq(post_url(post1, likes_page: total_likes_page))
        get json["users_liked"]["_links"]["next_page"], **@opts
        expect(json["users_liked"]["_links"]["prev_page"]).to eq(post_url(post1, likes_page: 1))
        expect(json["users_liked"]["_links"]["url"]).to eq(post_url(post1, likes_page: 2))
        get json["users_liked"]["_links"]["last_page"], **@opts
        expect(json["users_liked"]["_links"]["first_page"]).to eq(post_url(post1, likes_page: 1))
        expect(json["users_liked"]["_links"]["next_page"]).to be_nil
      end
    end

    context "with comments" do
      it "returns post comments" do
        post1 = create :post
        post1.comments << create_list(:comment, 3, post: post1)
        get post_url(post1), headers: valid_headers, as: :json
        expect(json["comments"]).not_to be_nil
      end

      it "paginates post comments in ascending order of creation time" do
        post1 = create :post
        random_count = rand((rand(2..4) * Comment.per_page)..(rand(5..8) * Comment.per_page))
        create_list(:comment, random_count, post: post1)

        token = token_for(create :user)
        @opts = { xhr: true, headers: { 'Authorization': token } }
        get post_url(post1), **@opts

        # check ascending order
        expect(json["comments"]["data"][0]["id"] < json["comments"]["data"][-1]["id"]).to be_truthy

        expect(json["comments"]["data"].length).to eq(Comment.per_page)
        expect(json["comments"]["_pagination"]["count"] <= Comment.per_page).to be_truthy
        expect(json["comments"]["_pagination"]["total_count"]).to eq(post1.comments.count)
        expect(json["comments"]["_links"]["next_page"]).to eq(post_url(post1, comments_page: 2))
        total_comments_page = (post1.comments.count / Comment.per_page.to_f).ceil
        expect(json["comments"]["_links"]["last_page"]).to eq(post_url(post1, comments_page: total_comments_page))
        get json["comments"]["_links"]["next_page"], **@opts
        expect(json["comments"]["_links"]["prev_page"]).to eq(post_url(post1, comments_page: 1))
        expect(json["comments"]["_links"]["url"]).to eq(post_url(post1, comments_page: 2))
        get json["comments"]["_links"]["last_page"], **@opts
        expect(json["comments"]["_links"]["first_page"]).to eq(post_url(post1, comments_page: 1))
        expect(json["comments"]["_links"]["next_page"]).to be_nil
      end
    end
  end

  describe "POST /create" do
    it "returns 401 unauthorized when user is unauthenticated" do
      post posts_url,
           params: { post: valid_attributes }, as: :json
      expect(response).to have_http_status(:unauthorized)
    end

    context "with valid parameters" do
      it "creates a new Post" do
        expect {
          post posts_url,
               params: { post: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Post, :count).by(1)
        expect(Post.last.image.persisted?).to be_nil
      end

      it "renders a JSON response with the new post" do
        post posts_url,
             params: { post: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end

      it "creates a new post with image" do
        valid_attributes[:image] = Rack::Test::UploadedFile.new("#{Rails.root}/spec/fixtures/user.jpg")
        post posts_url, xhr: true,
                        params: { post: valid_attributes }, headers: valid_headers
        expect(Post.last.image.persisted?).not_to be_nil
        expect(Post.last.body).to eq valid_attributes[:body]
      end
    end

    context "with invalid parameters" do
      it "does not create a new Post" do
        expect {
          post posts_url,
               params: { post: invalid_attributes }, as: :json
        }.to change(Post, :count).by(0)
      end

      it "renders a JSON response with errors for the new post" do
        post posts_url,
             params: { post: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    let!(:post1) { create :post, user: user }

    it "returns 401 unauthorized when user is unauthenticated" do
      delete post_url(post1), as: :json
      expect(response).to have_http_status(:unauthorized)
    end

    it "returns 403 forbidden when user is not owner of post" do
      delete post_url(create(:post)), headers: valid_headers, as: :json
      expect(response).to have_http_status(:forbidden)
      expect(json["message"]).to eq "Only the author of the post is allowed perform this operation"
    end

    it "destroys the requested post" do
      expect {
        delete post_url(post1), headers: valid_headers, as: :json
      }.to change(Post, :count).by(-1)
    end
  end
end
